version: '3'

services:
  app:
    container_name: api
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
  mongodb:
    image: mongo
    volumes:
      - ./database:/data/db
